apiVersion: v2
name: g-fe-server
description: A Helm chart for Kubernetes to deploy the Go-based presentation server with a sample react application.

type: application

version: 0.1.0

appVersion: "0.0.1"

dependencies:
  - name: mongodb
    version: 15.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
