# stack for development purposes
services:

  go_db:
    image: mongo:7.0
    platform: linux/arm64/v8
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: go_root
      MONGO_INITDB_ROOT_PASSWORD: go_password
      MONGO_INITDB_DATABASE: fe_db
    ports:
      - "27017:27017"
    volumes:
      - ./imports/init_db.d:/docker-entrypoint-initdb.d
      - fe_data:/data/db
    networks:
      - fe-private-network

  mongo-express:
    image: mongo-express:latest
    platform: linux/arm64/v8
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - "go_db"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: go_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: go_password
      ME_CONFIG_MONGODB_SERVER: go_db
    networks:
      - fe-private-network

  iam:
    image: quay.io/keycloak/keycloak:26.0
    platform: linux/arm64
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      JAVA_OPTS_APPEND: "-XX:UseSVE=0"
    volumes:
      - ./imports/realm:/opt/keycloak/data/import
    network_mode: "host"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    platform: linux/arm64
    volumes:
      - ./imports/otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 8889:8889 # Prometheus metrics
    networks:
      - fe-private-network

  zipkin:
    image: openzipkin/zipkin-slim:3
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - fe-private-network

networks:
  fe-private-network:

volumes:
  fe_data:
