# stack for development purposes
services:

  go_db:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: go_root
      MONGO_INITDB_ROOT_PASSWORD: go_password
      MONGO_INITDB_DATABASE: go_db
    ports:
      - "27017:27017"
    volumes:
      - ./imports/init_db.d:/docker-entrypoint-initdb.d
      - fe_data:/data/db
    networks:
      - fe-private-network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: unless-stopped
    ports:
      - 28080:8081
    depends_on:
      - "go_db"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: go_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: go_password
      ME_CONFIG_MONGODB_SERVER: go_db
    networks:
      - fe-private-network

networks:
  fe-private-network:

volumes:
  fe_data:
