# stack for development purposes
services:

  # go_db:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: go_root
  #     MONGO_INITDB_ROOT_PASSWORD: go_password
  #     MONGO_INITDB_DATABASE: fe_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./imports/init_db.d:/docker-entrypoint-initdb.d
  #     - fe_data:/data/db
  #   networks:
  #     - fe-private-network

  # mongo-express:
  #   image: mongo-express:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - "go_db"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: go_root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: go_password
  #     ME_CONFIG_MONGODB_SERVER: go_db
  #   networks:
  #     - fe-private-network

  kc_db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DBPOSTGRES_USER: keycloak
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 18080:8080

  iam:
    image: quay.io/keycloak/keycloak:26.1
    restart: unless-stopped
    depends_on:
      - "kc_db"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: "localhost"
    network_mode: "host"

  # zipkin:
  #   image: openzipkin/zipkin:latest
  #   restart: unless-stopped
  #   ports:
  #     - 9411:9411
  #   networks:
  #     - fe-private-network

  # prometheus:
  #   image: prom/prometheus:latest
  #   restart: unless-stopped
  #   ports:
  #     - 48080:9090
  #   networks:
  #     - fe-private-network

networks:
  fe-private-network:

volumes:
  fe_data:
  postgresql_data:
