# stack for development purposes
services:

  go_db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: go_root
      MONGO_INITDB_ROOT_PASSWORD: go_password
      MONGO_INITDB_DATABASE: fe_db
    ports:
      - "27017:27017"
    volumes:
      - ./imports/init_db.d:/docker-entrypoint-initdb.d
      - fe_data:/data/db
    networks:
      - fe-private-network

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 18080:8081
    depends_on:
      - "go_db"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: go_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: go_password
      ME_CONFIG_MONGODB_SERVER: go_db
    networks:
      - fe-private-network

  kc_db:
    image: docker.io/bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      POSTGRESQL_USERNAME: keycloak
      POSTGRESQL_DATABASE: keycloak
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - fe-private-network

  iam:
    image: docker.io/bitnami/keycloak:latest
    restart: unless-stopped
    ports:
      - 28080:8080
    depends_on:
      - "kc_db"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: kc_db
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
    networks:
      - fe-private-network

  # zipkin:
  #   image: openzipkin/zipkin:latest
  #   restart: unless-stopped
  #   ports:
  #     - 38080:9411
  #   networks:
  #     - fe-private-network

  # prometheus:
  #   image: prom/prometheus:latest
  #   restart: unless-stopped
  #   ports:
  #     - 48080:9090
  #   networks:
  #     - fe-private-network

networks:
  fe-private-network:

volumes:
  fe_data:
  postgresql_data:
