# stack for development purposes
services:

  go_db:
    image: mongo:7.0
    platform: linux/arm64/v8
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: go_root
      MONGO_INITDB_ROOT_PASSWORD: go_password
      MONGO_INITDB_DATABASE: fe_db
    ports:
      - "27017:27017"
    volumes:
      - ./imports/init_db.d:/docker-entrypoint-initdb.d
      - fe_data:/data/db
    networks:
      - fe-private-network

  mongo-express:
    image: mongo-express:latest
    platform: linux/arm64/v8
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - "go_db"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: go_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: go_password
      ME_CONFIG_MONGODB_SERVER: go_db
    networks:
      - fe-private-network

  iam:
    image: quay.io/keycloak/keycloak:26.0
    platform: linux/arm64
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      JAVA_OPTS_APPEND: "-XX:UseSVE=0"
    volumes:
      - ./imports/realm:/opt/keycloak/data/import
    network_mode: "host"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    platform: linux/arm64
    volumes:
      - ./imports/otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
    networks:
      - fe-private-network

  zipkin:
    image: openzipkin/zipkin-slim:3
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "9411:9411"
    depends_on:
      - "otel-collector"
    networks:
      - fe-private-network

  prometheus:
    image: prom/prometheus:v3.2.1
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./imports/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - "otel-collector"
    networks:
      - fe-private-network

  unleash:
    image: unleashorg/unleash-server:6.7
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "4242:4242"
    depends_on:
      - "feature-db"
    environment:
      DATABASE_HOST: feature-db
      DATABASE_NAME: feat_db
      DATABASE_USERNAME: feat_user
      DATABASE_PASSWORD: feat_password
      DATABASE_SSL: false
    networks:
      - fe-private-network

  unleash-edge:
    image: unleashorg/unleash-edge:v19.7
    platform: linux/amd64
    command: ["edge"]
    restart: unless-stopped
    ports:
      - "3063:3063"
    depends_on:
      - "unleash"
    environment:
      UPSTREAM_URL: http://unleash:4242/
      TOKENS: "default:development.f9e56e74a070c76b577840b2adb2ca195d394a2c3bd8915a93e6d617"
      STRICT: true
    networks:
      - fe-private-network

  feature-db:
    image: postgres:17.4
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_USER: feat_user
      POSTGRES_PASSWORD: feat_password
      POSTGRES_DB: feat_db
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - fe-private-network
    volumes:
      - unleash_data:/var/lib/postgresql/data


networks:
  fe-private-network:

volumes:
  fe_data:
  prometheus-data:
  unleash_data:
