apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "g-fe-server.fullname" . }}
  labels:
    {{- include "g-fe-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.g_fe_server.autoscaling.enabled }}
  replicas: {{ .Values.g_fe_server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "g-fe-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.g_fe_server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "g-fe-server.labels" . | nindent 8 }}
        {{- with .Values.g_fe_server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.g_fe_server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "g-fe-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.g_fe_server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.g_fe_server.securityContext | nindent 12 }}
          image: "{{ .Values.g_fe_server.image.repository }}:{{ .Values.g_fe_server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.g_fe_server.image.pullPolicy }}
          env:
            - name: CONTEXT_ROOT
              value: {{ .Values.g_fe_server.contextRoot | quote }}
            - name: ENABLE_OTEL_EXPORT
              value: {{ .Values.otlp.enabled | quote }}
            - name: OTLP_URL
              value: {{ .Values.otlp.endpoint | quote }}
            - name: OIDC_ISSUER
              value: {{ .Values.oidc.issuer | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientId | quote }}
            - name: OIDC_CLIENT_SECRET
              value: {{ .Values.oidc.clientSecret | quote }}
            - name: OIDC_SCOPES
              value: {{ .Values.oidc.scopes | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.g_fe_server.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/g/health"
              port: http
          readinessProbe:
            httpGet:
              path: "/g/health"
              port: http
          resources:
            {{- toYaml .Values.g_fe_server.resources | nindent 12 }}
          {{- with .Values.g_fe_server.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.g_fe_server.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.g_fe_server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.g_fe_server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.g_fe_server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
