{{- if .Values.g_fe_server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "g-fe-server.serviceAccountName" . }}
  labels:
    {{- include "g-fe-server.labels" . | nindent 4 }}
  {{- with .Values.g_fe_server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.g_fe_server.serviceAccount.automount }}
{{- end }}
