{{- if .Values.g_be_example.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "g-be-example.serviceAccountName" . }}
  labels:
    {{- include "g-be-example.labels" . | nindent 4 }}
  {{- with .Values.g_be_example.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.g_be_example.serviceAccount.automount }}
{{- end }}
